server:
  port: 8091

# 线程池配置
thread:
  pool:
    executor:
      core-pool-size: 20
      max-pool-size: 50
      keep-alive-time: 5000
      block-queue-size: 5000
      policy: CallerRunsPolicy

#dynamic:
#  thread:
#    pool:
#      enabled: true
#      host: 127.0.0.1
#      port: 16379

logging:
  level:
    web: info
